<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
        [
            'ID' => 1,
            'name' => 'SGM',
            'variant' => 'Stads Gewestelijk Materieel 1+2',
            'topspeed' => 125,
            'weight' => 106,
            'voltage' => '1.5kV',
            'traction' => 'electric',
            'system' => 'ATB-EG',
            'length' => 52,
            'coaches' => 2,
            'price' => '99.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 142,
            'manufacturer' => NULL,
            'fullname' => 'Stads Gewestelijk Materieel',
            'coupling' => 'scharfenbergkoppeling'
        ],[
            'ID' => 2,
            'name' => 'VIRM',
            'variant' => 'VIRM4 2/3',
            'topspeed' => 140,
            'weight' => 234,
            'voltage' => '1.5kV',
            'traction' => 'electric',
            'system' => 'ATB-EG',
            'length' => 109,
            'coaches' => 4,
            'price' => '199.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 387,
            'manufacturer' => 'Talboth/Bombardier',
            'fullname' => 'Verlengd Interregio Materieel',
            'coupling' => 'scharfenbergkoppeling'
        ],[
            'ID' => 3,
            'name' => 'NS 1700',
            'variant' => 'NS E-loc 1700',
            'topspeed' => 180,
            'weight' => 86,
            'voltage' => '1.5kV',
            'traction' => 'electric',
            'system' => 'ATB-EG + ATB-Vv',
            'length' => 18,
            'coaches' => NULL,
            'price' => '299.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => NULL,
            'manufacturer' => 'Jeumont/Schneider',
            'fullname' => 'NS 1700',
            'coupling' => 'schroefkoppeling'
        ],[
            'ID' => 4,
            'name' => 'ICM',
            'variant' => 'NS InterCityMaterieel 4',
            'topspeed' => 160,
            'weight' => 192,
            'voltage' => '1.5kV',
            'traction' => 'electric',
            'system' => 'ATB-EG',
            'length' => 107,
            'coaches' => 4,
            'price' => '399.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 300,
            'manufacturer' => 'Talbot/CEM Oerlikon/Holec',
            'fullname' => 'InterCityMaterieel',
            'coupling' => 'scharfenbergkoppeling'
        ],[
            'ID' => 5,
            'name' => 'Railion 6400',
            'variant' => 'MaK DE 6400',
            'topspeed' => 120,
            'weight' => 83,
            'voltage' => NULL,
            'traction' => 'diesel-electric',
            'system' => 'ATB + PZB + Memor + ERTMS',
            'length' => 14,
            'coaches' => NULL,
            'price' => '499.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => NULL,
            'manufacturer' => 'MaK/Vossloh',
            'fullname' => 'MaK DE 6400',
            'coupling' => 'schroefkoppeling'
        ],[
            'ID' => 6,
            'name' => 'NS TRAXX',
            'variant' => 'NS TRAXX br 186 es 64F',
            'topspeed' => 160,
            'weight' => 84,
            'voltage' => '1.5kV, 3kV, 15kV, 25kV',
            'traction' => 'electric',
            'system' => 'ETCS-L0,1&2 + ATB-EG + ERTMS PZB + MEMOR',
            'length' => 19,
            'coaches' => NULL,
            'price' => '599.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => NULL,
            'manufacturer' => 'bombardier',
            'fullname' => 'NS TRAXX',
            'coupling' => 'schroefkoppeling'
        ],[
            'ID' => 7,
            'name' => 'NS Flirt',
            'variant' => 'Flinker Leichter Innovativer Regionaltriebzug',
            'topspeed' => 160,
            'weight' => 138,
            'voltage' => '1.5kV',
            'traction' => 'electric',
            'system' => 'ATB-EG',
            'length' => 63,
            'coaches' => 3,
            'price' => '699.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 158,
            'manufacturer' => 'Stadler Rail',
            'fullname' => 'NS FLIRT',
            'coupling' => 'Scharfenbergloppeling'
        ],[
            'ID' => 8,
            'name' => 'SLT',
            'variant' => 'Sprinter Light Train 4',
            'topspeed' => 160,
            'weight' => 129,
            'voltage' => '1.5kV',
            'traction' => 'electric',
            'system' => 'ATB-EG + ERTMS L1/2',
            'length' => 69,
            'coaches' => 4,
            'price' => '799.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 216,
            'manufacturer' => 'Bombardier',
            'fullname' => 'Sprinter Light Train',
            'coupling' => 'Scharfenbergkoppeling'
        ],[
            'ID' => 9,
            'name' => 'SNG',
            'variant' => 'Sprinter Nieuwe Generatie 4',
            'topspeed' => 160,
            'weight' => 138,
            'voltage' => '1.5kV',
            'traction' => 'electric',
            'system' => 'ATB-EG + ERTMS',
            'length' => 76,
            'coaches' => 4,
            'price' => '899.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 160,
            'manufacturer' => 'CAF',
            'fullname' => 'Sprinter Nieuwe Generatie',
            'coupling' => 'Scharfenbergkoppeling'
        ],[
            'ID' => 10,
            'name' => 'mat \'64',
            'variant' => 'Materieel 1964, plan V V13',
            'topspeed' => 140,
            'weight' => 86,
            'voltage' => '1.5kV',
            'traction' => 'electric',
            'system' => 'ATB-EG',
            'length' => 82,
            'coaches' => 2,
            'price' => '999.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 153,
            'manufacturer' => 'Talbot',
            'fullname' => 'Mat \'64 plan V',
            'coupling' => 'Scharfenbergkoppeling'
        ],[
            'ID' => 11,
            'name' => 'dm \'90',
            'variant' => 'NS Dieselmaterieel 1990',
            'topspeed' => 140,
            'weight' => 95,
            'voltage' => NULL,
            'traction' => 'diesel',
            'system' => 'ATB-NG + PZB',
            'length' => 52,
            'coaches' => 2,
            'price' => '1099.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 153,
            'manufacturer' => 'Talbot',
            'fullname' => 'Dieselmaterieel 90',
            'coupling' => 'Scharfenbergkoppeling'
        ],[
            'ID' => 12,
            'name' => 'ICR(m)',
            'variant' => 'Intercityrijtuig gemoderniseerd',
            'topspeed' => 160,
            'weight' => 41,
            'voltage' => '1.5kV, 3kV, 15kV, 25kV',
            'traction' => NULL,
            'system' => NULL,
            'length' => 26,
            'coaches' => 1,
            'price' => '1199.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 80,
            'manufacturer' => 'Talbot',
            'fullname' => 'Intercityrijtuig',
            'coupling' => 'schoefkoppeling'
        ],[
            'ID' => 13,
            'name' => 'ICRm Stuurstand',
            'variant' => 'Intercityrijtuig gemoderniseerd stuurstandrijtuig',
            'topspeed' => 160,
            'weight' => 41,
            'voltage' => '1.5kV, 3kV, 15kV, 25kV',
            'traction' => NULL,
            'system' => NULL,
            'length' => 26,
            'coaches' => 1,
            'price' => '1299.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 80,
            'manufacturer' => 'Talbot',
            'fullname' => 'Intercity stuurstandrijtuig',
            'coupling' => 'schoefkoppeling'
        ],[
            'ID' => 14,
            'name' => 'mat \'54',
            'variant' => 'Materieel 1954 EID-4 Plan P',
            'topspeed' => 140,
            'weight' => 210,
            'voltage' => '1.5kV',
            'traction' => 'electric',
            'system' => 'ATB-EG',
            'length' => 99,
            'coaches' => 4,
            'price' => '1399.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 280,
            'manufacturer' => 'Allan, Beijnes, Werkspoor',
            'fullname' => 'Materieel \'54',
            'coupling' => 'scharfenbergkoppeling (laag)'
        ],[
            'ID' => 15,
            'name' => 'mat \'57',
            'variant' => 'Materieel 1957 Benelux',
            'topspeed' => 140,
            'weight' => 115,
            'voltage' => '1.5kV',
            'traction' => 'electric',
            'system' => 'ATB-EG, MEMOR',
            'length' => 50,
            'coaches' => 2,
            'price' => '1499.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 119,
            'manufacturer' => 'Allan, Beijnes, Werkspoor',
            'fullname' => 'Materieel \'57',
            'coupling' => 'scharfenbergkoppeling (laag)'
        ],[
            'ID' => 16,
            'name' => 'NS 1200',
            'variant' => 'NS E-loc 1200',
            'topspeed' => 150,
            'weight' => 108,
            'voltage' => '1.5kV',
            'traction' => 'electric',
            'system' => 'ATB',
            'length' => 18,
            'coaches' => NULL,
            'price' => '1599.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 119,
            'manufacturer' => 'Werkspoor',
            'fullname' => 'NS 1200',
            'coupling' => 'shroefkoppeling'
        ],[
            'ID' => 17,
            'name' => 'DDZ',
            'variant' => 'Dubbeldekker Zonering 6',
            'topspeed' => 140,
            'weight' => 319,
            'voltage' => '1.5kV',
            'traction' => 'electric',
            'system' => 'ATB-EG',
            'length' => 153,
            'coaches' => 6,
            'price' => '1699.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 119,
            'manufacturer' => 'NedTrain',
            'fullname' => 'NS Dubbeldekker Zonering ',
            'coupling' => 'scharfenbergkoppeling'
        ],[
            'ID' => 18,
            'name' => 'Vectron',
            'variant' => 'Siemens Vectron AC/DC',
            'topspeed' => 200,
            'weight' => 85,
            'voltage' => '1.5kV, 3kV, 15kV, 25kV',
            'traction' => 'electric',
            'system' => 'ATB-EG + ERTMS + ECTS + MEMOR',
            'length' => 19,
            'coaches' => NULL,
            'price' => '1799.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 119,
            'manufacturer' => 'Siemens',
            'fullname' => 'Siemens Vectron',
            'coupling' => 'schroefkoppeling + C-AKv'
        ],[
            'ID' => 19,
            'name' => 'DE3',
            'variant' => 'Plan U DE3',
            'topspeed' => 125,
            'weight' => 136,
            'voltage' => NULL,
            'traction' => 'diesel-electric',
            'system' => 'ATB-EG + ATB-NG',
            'length' => 74,
            'coaches' => 3,
            'price' => '1899.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 119,
            'manufacturer' => 'Werkspoor',
            'fullname' => 'Plan U',
            'coupling' => 'scharfenbergkoppeling'
        ],[
            'ID' => 20,
            'name' => 'Apmz',
            'variant' => 'Intercityrijtuig Apmz',
            'topspeed' => 200,
            'weight' => 41,
            'voltage' => '1.5kV, 3kV, 15kV, 25kV',
            'traction' => NULL,
            'system' => NULL,
            'length' => 26,
            'coaches' => NULL,
            'price' => '1999.99',
            'description' => 'Your bones don\'t break, mine do. That\'s clear. We swallow it too fast, we choke.',
            'seats' => 80,
            'manufacturer' => 'Talbot',
            'fullname' => 'Intercityrijtuig Apmz',
            'coupling' => 'schoefkoppeling'
        ]
        ]);
    }
}